title: Basic Income Guarantee Foundation
email: info@big.foundation
description: > # this means to ignore newlines until "baseurl:"
  A basic income (also called basic income guarantee, Citizen's Income, unconditional basic income, universal basic income (UBI), or universal demogrant) is a form of social security in which all citizens or residents of a country receive a regular, unconditional sum of money, either from a government or some other public institution, independent of any other income.

#twitter_username: macrod68
#github_username:  macrod68

sass:
    style: compressed